import{a as c,S as m,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const y="52950914-a47a655b15acf3b435807e601";c.defaults.baseURL="https://pixabay.com/api/";function d(o){return console.log("query",o),c.get("",{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:r})=>r).catch(r=>{console.log(r)})}let p=new m(".gallery a",{captionDelay:250,enableKeyboard:!0,showCounter:!0,scrollZoom:!0,loop:!0,overlayOpacity:.9,animationSpeed:250});function g(o){return o.map(({webformatURL:r,largeImageURL:i,tags:n,likes:e,views:t,comments:s,downloads:f})=>`<li class="gallery__item">
                <a class="gallery__link" href="${i}">
                    <img class="gallery__image" src="${r}" alt="${n}" />
                    <div class="info">
                        <p><b>Likes:</b> ${e}</p>
                        <p><b>Views:</b> ${t}</p>
                        <p><b>Comments:</b> ${s}</p>
                        <p><b>Downloads:</b> ${f}</p>
                    </div>
                </a>
            </li>`).join("")}function h(o){const r=document.querySelector(".gallery");r.innerHTML=g(o),p.refresh()}const b=document.querySelector(".form"),l=document.querySelector(".gallery"),u=document.querySelector(".loader");function L(){u.classList.add("visible")}function v(){u.classList.remove("visible")}b.addEventListener("submit",S);function S(o){o.preventDefault();const r=o.currentTarget.elements["search-text"].value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query!"});return}l&&(l.innerHTML=""),L(),d(r).then(i=>{if(i.hits.length===0)return a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});h(i.hits)}).catch(i=>console.log(i)).finally(()=>{v()})}
//# sourceMappingURL=index.js.map
