import{a as s,S as f,i as l}from"./assets/vendor-BSTwZ_tR.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const y="52950914-a47a655b15acf3b435807e601";s.defaults.baseURL="https://pixabay.com/api/";function m(t){return console.log("query",t),s.get("",{params:{key:y,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:r})=>r).catch(r=>{console.log(r)})}let d=new f(".gallery a",{captionDelay:250,enableKeyboard:!0,showCounter:!0,scrollZoom:!0,loop:!0,overlayOpacity:.9,animationSpeed:250});const c=document.querySelector(".loader");function p(){c.classList.add("visible")}function g(){c.classList.remove("visible")}function h(){const t=document.querySelector(".gallery");t&&(t.innerHTML="")}function b(t){return t.map(({previewURL:r,largeImageURL:n,tags:i,likes:e,views:o,comments:a,downloads:u})=>`<li class="gallery__item">
                <a class="gallery__link" href="${n}">
                    <img class="gallery__image" src="${r}" alt="${i}" />
                    <div class="info">
                        <p><b>Likes:</b> ${e}</p>
                        <p><b>Views:</b> ${o}</p>
                        <p><b>Comments:</b> ${a}</p>
                        <p><b>Downloads:</b> ${u}</p>
                    </div>
                </a>
            </li>`).join("")}function L(t){const r=document.querySelector(".gallery");r.innerHTML=b(t),d.refresh()}const S=document.querySelector(".form");document.querySelector(".gallery");S.addEventListener("submit",q);function q(t){t.preventDefault();const r=t.currentTarget.elements["search-text"].value.trim();if(!r){l.error({title:"Error",message:"Please enter a search query!"});return}h(),p(),m(r).then(n=>{if(n.hits.length===0)return l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});L(n.hits)}).catch(n=>console.log(n)).finally(()=>{g()})}
//# sourceMappingURL=index.js.map
